### PR TITLE
fix: add transformer to header params for proxy-rewrite and response-…

### PR DESCRIPTION
**Pull request by liuxiran**
fix: https://github.com/apache/apisix/issues/2082
fix: https://github.com/apache/apisix/issues/2087

Solution: https://github.com/apache/apisix/issues/2082#issuecomment-716364969

### CODE REVIEW

**Comment by membphis** [comment]
@liuxiran pls sign the CLA

**Comment by liuxiran** [comment]
> @liuxiran pls sign the CLA

thanks for your reminding, already done 😊

**Comment by juzhiyuan** [comment]
@liuxiran 嗨，请更新对应插件的 package.json 中的版本号。

**Comment by liuxiran** [comment]
> @liuxiran 嗨，请更新对应插件的 package.json 中的版本号。

ok, already done :)

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
Just published

**Pull request merged**
